Frontend MVP for Source Academy Rook
source-academy/frontend pull request #1878
Opened 2021-07-28 10:09 UTC by chownces

### Description

Frontend MVP for Source Academy Rook

#### Status:
- ~To get feedback on UI~
- Need to set up auth providers (Google, Github)
- ~Frontend mockups not updated yet~
- ~'Paths' logic is yet to be refactored~
- ~Assessment 'Grade' has not been fully removed~
- ~To relook at course 'viewability' for admins (it is currently disabled for all when viewable == false)~
- Check that achievements are working properly

Note: To temporarily disable the create course button for deployment

#### Changelog (Knight --> Rook):
- Added multitenant functionality 
    - UI for running multiple courses concurrently on our new backend
    - Users can now create new courses, or enroll in multiple courses

- Updated frontend routing
    - There are now 3 main possible deployment configurations:
        1. Source Academy @ NUS: uses the backend
            - Playground and Sourcecast are now hidden behind the login and are no longer publicly accessible
            - The new SICPJS feature is also hidden behind the login
        2. Playground-only: does not use the backend
            - No notable changes in routing
            - The new SICPJS feature is publicly accessible
        3. Source Academy with GitHub Classroom: an extension of 1 and 2 
            - Enables the GitHub Classroom functionality in either deployment
            - Publicly accessible in either deployment

- Updates to setting of course configuration
    - Previously, the game and achievements were disabled via environment variables in the frontend
    - Now, they are persisted in the backend by course. Different courses can enable/ disable different features at the same time

- New admin panel for course admins
    - Course settings such as course name, user management and toggling of features can now be done in this new admin panel
    - Hardcoded to allow upserts of up to 1000 users at a time

- Changes to testcase types
    - Not much change to the behaviour of these types on the frontend, the changes were mostly due to backend refactoring
    - Previously: Public, Hidden and Private
    - Now: Public, Opaque and Secret

- 'Grade' metric has been deprecated. Assessments will now solely use XP for grading.

### Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### How to test

To be tested with the new backend (https://github.com/source-academy/backend/pull/775)

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

2021-07-28 10:10 UTC, chownces commented
Accidentally merged in the previous PR ==. Reissuing it here

2021-07-28 10:16 UTC, chownces commented on src/commons/achievement/utils/InsertFakeAchievements.ts
> +        assessmentOverview.type === 'Missions' || assessmentOverview.type === 'Paths'
probably need the achievements team to remove this hardcode

2021-07-28 10:16 UTC, chownces commented on src/commons/achievement/utils/InsertFakeAchievements.ts
> +        completionText: `XP: ${assessmentOverview.xp} / ${assessmentOverview.maxXp}`
and relook this

2021-07-28 10:16 UTC, chownces commented on src/pages/academy/adminPanel/subcomponents/AddUserPanel.tsx
> +    }
still hardcoded to 1000 per upload for now. will be relooked when the super user rights are implemented

2021-07-28 10:16 UTC, chownces commented on src/pages/contributors/subcomponents/ContributorsDetails.tsx
> +              join us!
requested by prof

2021-08-01 21:07 UTC, angelsl requested changes
Looks good mostly, just a few minor issues

2021-08-01 21:07 UTC, angelsl commented on src/pages/academy/adminPanel/subcomponents/assessmentConfigPanel/DeleteRowCell.tsx
> +            Are you sure you want to <b>delete</b> the assesment type <i>{props.data.type}</i>?
assesSment

2021-08-01 21:07 UTC, angelsl commented on src/pages/academy/adminPanel/subcomponents/assessmentConfigPanel/NumericCell.tsx
> +  field: AssessmentConfigNumericField;
Same comment as earlier

2021-08-01 21:07 UTC, angelsl commented on src/pages/welcome/Welcome.tsx
> +              You have logged in as <strong>{props.name}</strong>. Source Academy @ NUS does not
Maybe we should move this "Source Academy @ NUS" title to a configuration env var

2021-08-01 21:07 UTC, angelsl commented on src/pages/welcome/WelcomeContainer.ts
> +export default WelcomeContainer;
Let's use hooks (`useSelector`) instead of connected components please..

2021-08-01 21:11 UTC, angelsl commented
I left quite a few comments but I think the main issues are

- avoid accessing the Redux store via the `store` global as far as possible (this should be resolved once the course ID is in the URL, future PR)
- avoid hardcoding NUS and NUS-specific terms in new text (this one we can do in a future PR, it's fine)
- avoid using connected components for new components, use hooks e.g. `useSelector` instead
- also, any typos

2021-08-02 10:20 UTC, chownces commented on src/commons/achievement/utils/InsertFakeAchievements.ts
> +        assessmentOverview.type === 'Missions' || assessmentOverview.type === 'Paths'
Will be removing this categorisation as discussed. Probably in #1886

2021-08-03 07:38 UTC, angelsl approved these changes
Thanks for all the work!

2021-08-03 07:39 UTC, merged