Fix sessions button
source-academy/frontend pull request #2489
Opened 2023-05-22 12:22 UTC by vansh284

### Description

This PR aims to resolve https://github.com/source-academy/frontend/issues/2422. As mentioned by @shenyih0ng this issue is related to the switch to `AnchorButton`. Blueprintjs recommends the use of `AnchorButton` for tooltips over disabled buttons and so is required to resolve https://github.com/source-academy/frontend/issues/2417. However `AnchorButton` does not support submit buttons. 

The proposed solution is to use `AnchorButton` to render the `ControlButton` component only for disabled buttons. Buttons that are not disabled continue to use the regular Blueprintjs `Button`. Since `AnchorButton` and `Button` look the same, this shouldn't pose any problems. For reference https://blueprintjs.com/docs/#core/components/button.

Another possible and 'hacky' fix would be wrapping the `AnchorButton` with a HTML 'submit' button (refer to my first commit) but I prefer the current fix,

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### Checklist

- [x] I have tested this code

2023-05-22 19:31 UTC, vansh284 commented
> Is there any reason we want to keep using `Button` instead of `AnchorButton` when `isDisabled` is false?


`Button` allows passing in the HTML button type attribute so we are able to use our `ControlButton` component to submit form data. This does not work on `AnchorButton`. This is what caused the bug in the join sessions button in the first place.
![image](https://github.com/source-academy/frontend/assets/65393463/9e960349-6d02-4a07-8c5c-df3e5fec133d)

When `isDisabled` is true, no functionality is expected from the button, so we can switch to `AnchorButton` to allow the tooltips to function properly.

2023-05-23 05:33 UTC, RichDom2185 requested changes
Let's try to reduce duplicated code here.

2023-05-23 05:33 UTC, RichDom2185 commented on src/commons/ControlButton.tsx
> +
```suggestion
  // Refer to #2417 and #2422 for why we conditionally
  // set the button component. See also:
  // https://blueprintjs.com/docs/#core/components/button
  const ButtonComponent = isDisabled ? AnchorButton : Button;
```

2023-05-23 05:33 UTC, RichDom2185 commented on src/commons/ControlButton.tsx
> +    <Button
```suggestion
    <ButtonComponent
```

2023-05-23 05:33 UTC, RichDom2185 commented on src/commons/ControlButton.tsx
> +    </Button>
```suggestion
    </ButtonComponent>
```

2023-05-23 05:51 UTC, RichDom2185 approved these changes
LGTM, thanks!

2023-05-23 05:55 UTC, merged