Create contest configurations in ground control
source-academy/frontend pull request #2835
Opened 2024-03-06 13:56 UTC by jayjay19630

### Description

Since contests are a unique case of assessments, we have decided to create its own tab within ground control. This will help ease access to such contests while also making preparations for future configurations and controls that will be specific to contests (i.e. voting assignment controls, exporting leaderboards, etc).

For assessments to be considered contests, course configurations will also include a new toggle button called 'Is Contest Related', which replaces 'Has Token Counter.' Note that the toggling the presence of a token counter will now be embedded in this new 'Is Contest Related' toggle, as the only use case for token counters are contests.

### Type of change
- [ ] New feature (non-breaking change which adds functionality)

### Checklist
- [ ] I have tested this code

2024-03-06 15:13 UTC, DesSnowy commented
Corresponding backend PR: https://github.com/source-academy/backend/pull/1085

2024-03-07 05:34 UTC, RichDom2185 requested changes
Hi, thanks for working on this. I have some questions I want to clarify:

> Note that the feature of toggling token counters will now be embedded in this new 'Is Contest Related' toggle, as the only use case for token counters are contests.

Are you saying that there is no more toggle for token counter (refer to the code snippet below)? I would think that if we were to encapsulate all these settings, then it would still remain as a separate toggle?

2024-03-07 05:34 UTC, RichDom2185 commented on src/commons/assessmentWorkspace/AssessmentWorkspace.tsx
> +    props.assessmentConfiguration.isContestRelated,
Does this mean that any contest will always have a token counter enabled?

2024-03-07 08:41 UTC, jayjay19630 commented
The main purpose of this PR is so that contest specific assessments can have extra configurations like a button for assigning contest entries to students (see below).

<img width="1263" alt="Screenshot 2024-03-07 at 4 38 12 PM" src="https://github.com/source-academy/frontend/assets/142368471/edc26643-a323-4b4c-9b00-54a88bf3577d">

However, we've realised that by having only one 'isContestRelated' field, all contest assessmnets will have a switch for assigning entries, when we only want the contest (not voting) to have the switch. This makes it confusing as to how to actually assign the entries. We're working on a new field called "isContestVoting" to conditionally display the switch, so do expect some updates for that. In the meantime, I'll mark this PR as a draft.

2024-03-21 10:52 UTC, closed without merging