Transfer groundControl from staff to admin route
source-academy/frontend pull request #3043
Opened 2024-09-01 16:52 UTC by josh1248

### Description
Addresses #3031 by re-routing ground control from a staff to an admin route.
P.S.: still figuring out the backend. Will further changes be required?

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

- Enter the test environment as an admin, and see that you are able to enter ground control normally.
- Copy the ground control route (should be '/groundcontrol')
- Switch the test environment to be a staff
- Check that the ground control button is now missing.
- Paste the ground control route. A 404 route should be expected.

### Checklist

- [ ] I have tested this code
- [ ] I have updated the documentation

2024-09-01 17:12 UTC, RichDom2185 approved these changes
LGTM, thanks!

2024-09-01 17:12 UTC, RichDom2185 commented
Waiting for the BE PR before merging.

2024-09-08 18:07 UTC, RichDom2185 requested changes

2024-09-08 18:07 UTC, RichDom2185 commented on src/commons/sagas/RequestsSaga.ts
> + * GET /courses/{courseId}/staff/users/{studentCourseRegId}/goals
Let's not do this. `/admin` doesn't refer to the role; it refers to (course) administration.

It's a sub-resources belonging to the REST resource which is the course itself.

The role check is transparent (i.e. unknown to) the frontend; you shouldn't be able to tell based on the endpoint what are the checks.

2024-09-08 18:24 UTC, josh1248 commented
@RichDom2185 backend PR is ready now. I have replaced all non-dangerous routes to use a "/staff" instead of "/admin" URL to connect to the backend. I have also changed the routes in the backend directly. All seems good, but I am not sure if I have advertently broken some frontend-backend link. Any automated way to test it?

2024-09-08 18:35 UTC, RichDom2185 commented
> Any automated way to test it?

@josh1248 not really, I think best to just not touch it. Refer to my comments above. 

Basically your endpoints paths should be related to your resource. 

E.g. GET /users/{id}/name

or something like that

2024-09-24 06:37 UTC, RichDom2185 approved these changes
LGTM, thanks!

2024-09-24 06:40 UTC, merged